version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./server/src:/app/src
      - /server/node_modules
    environment:
      - DB_HOST=database
      - DB_PORT=3307
      - DB_USER=root
      - DB_DATABASE=stock_calculator

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./client/src:/app/src
      - ./client/index.html:/app/index.html
      - /client/node_modules
    ports:
      - "5173:5173"

  database:
    image: mysql:5.7
    ports:
      - "3307:3307"
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=stock_calculator
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_TCP_PORT=3307
