version: '3'
services:
  server:
    container_name: stock-calculator-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3307
      - DB_USER=root
      - DB_DATABASE=stock_calculator
      - APP_PORT=3000

  client:
    container_name: stock-calculator-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      - "5173:5173"
    environment:
      - APP_PORT=5173

  database:
    container_name: stock-calculator-database
    image: mysql:5.7
    ports:
      - "3307:3307"
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/x86_64
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=stock_calculator
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_TCP_PORT=3307